
//This file should be called cbmc_main_tool_detection_in_video.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_tool_detection_in_video.c F_tool_detection_in_video.c


#include "F_tool_detection_in_video.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for tool_detection_in_video
	enforcervars_tool_detection_in_video_t enf_tool_detection_in_video;
    inputs_tool_detection_in_video_t inputs_tool_detection_in_video;
    outputs_tool_detection_in_video_t outputs_tool_detection_in_video;

	//set values to known state
    tool_detection_in_video_init_all_vars(&enf_tool_detection_in_video, &inputs_tool_detection_in_video, &outputs_tool_detection_in_video);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_tool_detection_in_video.T1 = nondet_tool_detection_in_video_input_0();
	inputs_tool_detection_in_video.T2 = nondet_tool_detection_in_video_input_1();
	inputs_tool_detection_in_video.T3 = nondet_tool_detection_in_video_input_2();
	inputs_tool_detection_in_video.T4 = nondet_tool_detection_in_video_input_3();
	inputs_tool_detection_in_video.T5 = nondet_tool_detection_in_video_input_4();
	inputs_tool_detection_in_video.T6 = nondet_tool_detection_in_video_input_5();
	inputs_tool_detection_in_video.T7 = nondet_tool_detection_in_video_input_6();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_tool_detection_in_video._policy_p1_state = nondet_tool_detection_in_video_enf_p1_state() % 2;
	enf_tool_detection_in_video.v = nondet_tool_detection_in_video_enf_p2_0();
	
	enf_tool_detection_in_video._policy_p2_state = nondet_tool_detection_in_video_enf_p2_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	tool_detection_in_video_run_via_enforcer(&enf_tool_detection_in_video, &inputs_tool_detection_in_video, &outputs_tool_detection_in_video);

}


void tool_detection_in_video_run(inputs_tool_detection_in_video_t *inputs, outputs_tool_detection_in_video_t *outputs) {
    //randomise controller

    outputs->res = nondet_tool_detection_in_video_output_0();
	 
}

